/**
 * The line at the foot of a shared list: what made it, and when (the owner, 2026-09-17: "in the
 * end, the list is generated by cuddlecue on [date] [time]").
 *
 * Here, and not in `packages/core`, for two reasons. The app's name is read from
 * `assets/brand.json` and never typed — `assets/brand.test.ts` fails the build on a product name
 * written anywhere else — so the string has to come from the brand package, which core does not
 * depend on. And the date is a LOCAL one: the household's zone and the viewer's 12/24-hour
 * choice both live at the edge. Core takes the two finished facts and prints them.
 *
 * Pure, so the node suite can read the sentence back; nothing here imports React Native.
 */
import { BRAND } from '@nibblecue/brand';

/** `Sep 17, 2026 at 9:42 PM`, or the 24-hour form where that is what the phone is set to. */
export function stampedAt(
  at: number,
  clock24: boolean,
  timeZone?: string,
  locale = 'en-US',
): string {
  const date = new Intl.DateTimeFormat(locale, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    ...(timeZone === undefined ? {} : { timeZone }),
  }).format(at);
  const time = new Intl.DateTimeFormat(locale, {
    hour: 'numeric',
    minute: '2-digit',
    hour12: !clock24,
    ...(timeZone === undefined ? {} : { timeZone }),
  }).format(at);
  return `${date} at ${time}`;
}

/** What `shoppingText` signs a shared list with. */
export const listSignature = (
  at: number,
  clock24: boolean,
  timeZone?: string,
): { appName: string; at: string } => ({
  appName: BRAND.appDisplayName,
  at: stampedAt(at, clock24, timeZone),
});
