/**
 * ── GUIDANCE CARDS ────────────────────────────────────────────────────────────────────────────
 *
 * Published guidance in a sentence or three, each with its source. Never generated and never
 * about this baby's state: a card says what is common, not what is wrong (copy.banned.ts).
 * `guidance.data.test.ts` parses every card with the `GuidanceCard` schema and holds the copy
 * rules (no banned phrase, no sentence dash, US spelling, at most three sentences).
 */
import type { GuidanceCardInput } from './types';

export const GUIDANCE_DATA: readonly GuidanceCardInput[] = [
  {
    id: 'readiness-signs',
    title: 'Signs of readiness for solids',
    body: 'Most babies are ready for solids around 6 months. Readiness is about skills, not the calendar: steady head control, sitting with support and real interest in food.',
    points: [
      'Holds the head steady and upright.',
      'Sits with support.',
      'Reaches for things and brings them to the mouth.',
      'Watches you eat and reaches for your food.',
      'On the first tries, watch whether food goes back and is swallowed. Pushing it out is common at first.',
      'Solids are not recommended before 4 months.',
    ],
    trigger: 'getting_ready',
    fromMonths: 4,
    toMonths: 6,
    regions: [],
    sources: ['cdc-faqs', 'aap-starting-solids'],
  },
  {
    id: 'milk-is-main',
    title: 'Milk is still the main food',
    body: 'Until about 12 months, breast milk or formula gives most of what your baby needs. Food is for exploring and practice.',
    points: [
      'Offering milk first, then food, is common in the early months.',
      'Closer to 12 months, many families offer food first, then milk.',
    ],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 11,
    regions: [],
    sources: ['aap-starting-solids', 'usda-dga'],
  },
  {
    id: 'responsive-feeding',
    title: 'You decide what, your baby decides how much',
    body: 'You choose what to offer, and when and where. Your baby decides whether to eat and how much. Turning away, closing the mouth or pushing the spoon are common ways of saying "all done."',
    points: [
      "Follow your baby's pace, and stop when your baby shows signs of being full.",
      'Skip praise or rewards for finishing, and skip pressure to take one more bite.',
      'Eating amounts go up and down from day to day; that is common.',
    ],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['satter-sdor', 'cdc-mealtime'],
  },
  {
    id: 'how-much-to-start',
    title: 'How much to offer at first',
    body: 'Start with a teaspoon or two, once a day. Let your baby lead, and build slowly toward two or three meals a day over the next few months.',
    points: [
      'Watch your baby, not the bowl.',
      'Some days your baby will eat more, some days less.',
      'Never add cereal or other food to a bottle.',
    ],
    trigger: 'first_week',
    fromMonths: 6,
    toMonths: 8,
    regions: [],
    sources: ['raisingchildren-solids', 'unicef-6-12', 'aap-starting-solids'],
  },
  {
    id: 'seated-and-supervised',
    title: 'Upright, seated and close by',
    body: "Offer food with your baby sitting upright, in a high chair if you have one, and stay within arm's reach. Never feed in a car seat, stroller or bed, and never put cereal in a bottle.",
    points: [
      'Keep meals calm, with screens off.',
      'Older babies and toddlers also eat best seated, not while walking or playing.',
    ],
    trigger: 'first_week',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['aap-choking', 'cdc-faqs'],
  },
  {
    id: 'gagging-vs-choking',
    title: 'Gagging and choking are different',
    body: 'Gagging is common while learning to eat. It is loud, with coughing, sputtering and watery eyes, and it moves food forward. Choking is silent: no cough, no cry, and the skin can turn pale or blue.',
    points: [
      'Gagging is loud. Stay calm and let your baby work it out.',
      'Choking is silent or near silent, with no strong cough.',
      "Never sweep a finger through your baby's mouth.",
      'If your baby is choking, call emergency services and start infant first aid.',
      'An infant CPR and first aid course is worth taking before or soon after starting solids.',
    ],
    trigger: 'first_finger_food',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['nhs-choking', 'aap-choking'],
  },
  {
    id: 'safe-shapes',
    title: 'Shapes that lower choking risk',
    body: 'Cut round foods like grapes and cherry tomatoes lengthwise into quarters. Cook hard vegetables until soft, spread nut butters thinly, and remove pits, bones and tough skins.',
    points: [
      'Whole nuts, popcorn, hard candy and marshmallows stay off the menu until at least 4 years.',
      'Cheese is shredded or thinly sliced, never cubed.',
      'Raw hard vegetables and raw apple chunks wait until about 4 years.',
      'Cut most foods to about 1/2 inch or smaller once your baby eats small pieces.',
    ],
    trigger: 'first_finger_food',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['aap-choking'],
  },
  {
    id: 'allergen-basics',
    title: 'Introducing common allergens',
    body: 'Current guidance recommends introducing common allergens early and often. Offer one new allergen at a time, at home and earlier in the day, so you can watch for a few hours. Once it is tolerated, keep offering it a few times a week.',
    points: [
      'The common ones are egg, peanut, milk, wheat, soy, sesame, tree nuts, fish and shellfish.',
      'Start with a small amount mixed into a food your baby already eats.',
      'Leave a few days between new allergens.',
      'If your baby has severe eczema or an egg allergy, talk with your pediatrician about peanut around 4 to 6 months.',
    ],
    trigger: 'first_allergen',
    fromMonths: 4,
    toMonths: 24,
    regions: [],
    sources: ['aap-allergens', 'niaid-peanut'],
  },
  {
    id: 'possible-reaction',
    title: 'What a possible reaction can look like',
    body: 'Milder signs often show in one place, like a few hives or redness around the mouth. Call emergency services right away for trouble breathing, swelling of the face, lips or tongue, repeated vomiting, or a baby who turns pale or floppy.',
    points: [
      'Most reactions start within minutes to 2 hours of eating.',
      'Repeated vomiting 2 to 4 hours after a food can also be a reaction. Call your pediatrician.',
      'For milder signs, stop offering the food and call your pediatrician.',
      'Note what you saw and when, with a photo if you can.',
    ],
    trigger: 'first_allergen',
    fromMonths: 4,
    toMonths: 24,
    regions: [],
    sources: ['aap-allergens', 'niaid-peanut'],
  },
  {
    id: 'iron-often',
    title: 'Iron-rich foods, often',
    body: 'Babies need more iron from food starting around 6 months. Offer iron-rich foods often, like meat, beans, lentils, tofu, egg and iron-fortified cereal. Pair plant sources with a vitamin C food like tomato, orange or broccoli.',
    points: [
      'Iron from meat, poultry and fish is the easiest for the body to take in.',
      'Ask your pediatrician about iron if your baby is breastfed only.',
    ],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['cdc-iron', 'aap-vitamins'],
  },
  {
    id: 'rotate-grains',
    title: 'Rotate your grains',
    body: 'Rice cereal does not need to be the only first grain. Rotate oat, barley, multigrain, wheat and other grains for variety and to limit arsenic from rice.',
    points: ['Choose iron-fortified infant cereals.'],
    trigger: 'first_week',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['aap-starting-solids', 'cdc-iron'],
  },
  {
    id: 'lumps-by-nine',
    title: 'Moving on to lumps',
    body: 'Many babies move from smooth purees to mashed food with soft lumps within a few weeks. Aim to offer lumpy and finger foods by about 9 months, since practice with textures builds chewing skills.',
    points: [
      'Mash with a fork instead of blending.',
      'Soft finger foods help practice chewing and self-feeding.',
      'Gagging while learning new textures is common.',
    ],
    trigger: 'texture_step',
    fromMonths: 6,
    toMonths: 11,
    regions: [],
    sources: ['health-canada-6-24', 'nhs-7-9'],
  },
  {
    id: 'first-cup',
    title: 'Starting a cup',
    body: 'From about 6 months, offer a few sips of water from an open cup or straw cup with meals. Skip valved sippy cups, which work like a bottle. Small amounts are plenty, up to about 8 oz of water a day.',
    points: ['Hold the open cup at first and let your baby sip.', 'Spills are part of learning.'],
    trigger: 'cup',
    fromMonths: 6,
    toMonths: 11,
    regions: [],
    sources: ['aap-bottle', 'cdc-faqs'],
  },
  {
    id: 'bottle-weaning',
    title: 'Moving on from the bottle',
    body: 'Guidance suggests moving from bottles to cups between 12 and 18 months. Many families drop one bottle at a time, starting with the midday one and keeping the bedtime bottle for last.',
    points: ['Offer milk in a cup with meals.', 'A favorite cup can help.'],
    trigger: 'cup',
    fromMonths: 12,
    toMonths: 18,
    regions: [],
    sources: ['aap-bottle'],
  },
  {
    id: 'whole-milk',
    title: 'Whole milk from 12 months',
    body: "From 12 months, whole cow's milk can be offered as a drink, about 16 to 24 oz a day. More than 32 oz a day can leave less room for iron-rich foods. Fortified, unsweetened soy milk is an option for families who skip dairy.",
    points: [
      'Whole milk is recommended until age 2 unless your pediatrician advises otherwise.',
      'Offer milk from a cup with meals and snacks.',
      'Rice, oat and almond drinks are not a replacement for milk at this age.',
    ],
    trigger: 'cup',
    fromMonths: 12,
    toMonths: 24,
    regions: [],
    sources: ['cdc-milk', 'aap-toddler-milk'],
  },
  {
    id: 'juice',
    title: 'If you offer juice',
    body: 'No juice before 12 months. After that, juice is optional: at most 4 oz a day of 100% juice, with a meal and never in a bottle. Whole fruit is a great alternative.',
    points: ['Skip juice at bedtime.', 'Water and milk are the main drinks from 12 months.'],
    trigger: 'cup',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['aap-juice'],
  },
  {
    id: 'no-honey',
    title: 'No honey before 12 months',
    body: 'Honey can carry botulism spores that are dangerous for babies. Skip honey before 12 months, raw or cooked, including in baked foods and cereals.',
    points: ['Check labels on cereals, crackers and yogurts for honey.'],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 11,
    regions: [],
    sources: ['cdc-faqs', 'usda-dga'],
  },
  {
    id: 'no-added-sugar',
    title: 'No added sugar before 2',
    body: 'Guidance is to skip added sugars and sweetened drinks before age 2. Fruit gives natural sweetness, and babies learn to enjoy foods as they are.',
    points: [
      'Honey, syrups and table sugar all count as added sugars.',
      'Check labels on yogurts, cereals and snacks.',
    ],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['usda-dga'],
  },
  {
    id: 'salt-uk',
    title: 'Go easy on salt',
    body: "Babies under 12 months need less than 1 g of salt a day, and children aged 1 to 3 years no more than 2 g. Skip adding salt to your baby's food and go easy on salty foods like stock cubes, cheese and bread.",
    points: ['Cook the baby portion before adding salt for the rest of the family.'],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 24,
    regions: ['UK'],
    sources: ['nhs-salt'],
  },
  {
    id: 'stools-change',
    title: 'Stools change with solids',
    body: "It's common for stools to get firmer, smellier and change color once solids start, and to see bits of food. Prunes, pears, peaches and sips of water with meals can help soften things. Call your pediatrician for blood in the stool, green vomit, a swollen belly or pain.",
    points: [
      'Rice cereal and a lot of banana can firm stools.',
      'Beets can turn stools red, and leafy greens can turn them green.',
    ],
    trigger: 'stools',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['harvard-constipation'],
  },
  {
    id: 'refusal-is-information',
    title: 'A no today is information',
    body: "It's common for babies to refuse a new food many times before accepting it, and some foods take 10 to 15 tries. Keep offering small amounts in different ways, with no pressure.",
    points: [
      'Try a new shape, texture or pairing next time.',
      'Serve it next to a food your baby already enjoys.',
      'Eating with your baby helps.',
    ],
    trigger: 'refusal',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['satter-sdor', 'cdc-mealtime'],
  },
  {
    id: 'toddler-new-foods',
    title: 'Wary of new foods',
    body: "Many toddlers grow wary of new foods between 12 and 24 months, and it's common. Include one familiar food at each meal, eat together, and skip bribes and pressure.",
    points: [
      'Serve new foods next to ones your toddler already likes.',
      'Let your toddler touch, smell and play with new foods.',
      'A taste counts, and so does having it on the plate.',
    ],
    trigger: 'toddler',
    fromMonths: 12,
    toMonths: 24,
    regions: [],
    sources: ['satter-sdor', 'cdc-mealtime'],
  },
  {
    id: 'throwing-food',
    title: 'When food hits the floor',
    body: 'Dropping and throwing food is a common way babies explore and say they are done. Stay calm, offer small portions, and end the meal when the throwing starts.',
    points: ['A calm "food stays on the table" works better than a big reaction.'],
    trigger: 'toddler',
    fromMonths: 9,
    toMonths: 24,
    regions: [],
    sources: ['cdc-mealtime', 'satter-sdor'],
  },
  {
    id: 'snacks-uk',
    title: 'Meals before snacks',
    body: 'Snacks are not needed before 12 months; milk feeds and meals cover it. From 12 months, two snacks between meals are common.',
    points: [],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 24,
    regions: ['UK'],
    sources: ['nhs-7-9', 'nhs-10-12', 'nhs-over-12'],
  },
  {
    id: 'snacks-ca',
    title: 'Snacks between meals',
    body: 'Along with milk feeds and meals, one or two snacks a day are common for older babies. Offer snacks at planned times, with foods you would serve at a meal.',
    points: [],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 24,
    regions: ['CA'],
    sources: ['health-canada-6-24'],
  },
  {
    id: 'vitamin-d',
    title: 'Vitamin D for breastfed babies',
    body: 'AAP advises 400 IU of vitamin D a day for babies who are breastfed or partly breastfed, starting soon after birth. Ask your pediatrician which drops to use.',
    points: ['After 12 months, AAP advises 600 IU a day.'],
    trigger: 'always',
    fromMonths: 0,
    toMonths: 24,
    regions: ['US', 'CA'],
    sources: ['aap-vitamins'],
  },
  {
    id: 'daycare-handoff',
    title: 'Sharing the plan with caregivers',
    body: 'Share a short list with your caregivers: foods your baby eats, allergens in rotation, how you cut foods and which cup you use. Try new foods and new allergens at home first.',
    points: [
      'Agree on a start date for solids together.',
      'Ask how the daycare handles food allergies and new foods.',
    ],
    trigger: 'daycare',
    fromMonths: 4,
    toMonths: 24,
    regions: [],
    sources: ['aap-allergens', 'aap-choking'],
  },
  {
    id: 'feeding-on-the-go',
    title: 'Feeding on the go',
    body: 'Pack foods your baby already knows, and save new foods and new allergens for days at home. Keep cold foods cold, and toss leftovers that have been out for more than 2 hours.',
    points: ['Pouches and jars are handy for travel.', 'Bring a cup your baby knows.'],
    trigger: 'travel',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['cdc-food-safety-under-5', 'aap-allergens'],
  },
  {
    id: 'plant-based-families',
    title: 'Plant-based families',
    body: 'Vegan diets can work for babies with planning. Talk with your pediatrician about vitamin B12, and include iron-rich foods, fats and a source of omega-3, like ground flax, chia or hemp.',
    points: [
      "From 12 months, fortified unsweetened soy milk is the closest plant milk to cow's milk.",
      'Pair beans, lentils and tofu with a vitamin C food.',
    ],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['healthlink-vegan'],
  },
  {
    id: 'pouches-have-a-place',
    title: 'Pouches have a place',
    body: 'Pouches and jars are a handy option, especially on busy days. When you can, squeeze them onto a spoon so your baby practices spoon feeding and new textures.',
    points: ['Check labels for added sugar and allergens.'],
    trigger: 'always',
    fromMonths: 6,
    toMonths: 24,
    regions: [],
    sources: ['aap-starting-solids'],
  },
];
