/**
 * GENERATED by tools/ui/import-png-icons.mjs from assets/brand/kit/09-icons-illustrated — do not
 * edit. Add a picture by dropping its PNG there and running the command.
 *
 * THE PICTURES THEMSELVES. Separate from `illustrated.ts` because the node test runner cannot
 * parse an image `require` — Metro resolves it at build time, vitest tries to read it as
 * JavaScript — and the rules worth a test are the size threshold and the tier, which live in the
 * other file with no assets to trip over. They are PNG (the tool's header says why they are not
 * WebP).
 *
 * `require` IS THE API. React Native's asset pipeline has no import form — `import x from
 * './a.png'` gives Metro nothing to register, so the bundler's own `require` is the only way to
 * reach an image. Disabled for this file alone, which holds nothing but the paths.
 */
/* eslint-disable @typescript-eslint/no-require-imports */
import type { ImageSourcePropType } from 'react-native';
import type { IllustratedName, IllustratedTier } from './illustrated';

export const ILLUSTRATED_ICONS: Record<
  IllustratedName,
  Record<IllustratedTier, ImageSourcePropType>
> = {
  bath: {
    24: require('./illustrated/24/bath.png') as ImageSourcePropType,
    48: require('./illustrated/48/bath.png') as ImageSourcePropType,
  },
  bottle: {
    24: require('./illustrated/24/bottle.png') as ImageSourcePropType,
    48: require('./illustrated/48/bottle.png') as ImageSourcePropType,
  },
  breast: {
    24: require('./illustrated/24/breast.png') as ImageSourcePropType,
    48: require('./illustrated/48/breast.png') as ImageSourcePropType,
  },
  'care-other': {
    24: require('./illustrated/24/care-other.png') as ImageSourcePropType,
    48: require('./illustrated/48/care-other.png') as ImageSourcePropType,
  },
  'care-vitamin': {
    24: require('./illustrated/24/care-vitamin.png') as ImageSourcePropType,
    48: require('./illustrated/48/care-vitamin.png') as ImageSourcePropType,
  },
  diaper: {
    24: require('./illustrated/24/diaper.png') as ImageSourcePropType,
    48: require('./illustrated/48/diaper.png') as ImageSourcePropType,
  },
  growth: {
    24: require('./illustrated/24/growth.png') as ImageSourcePropType,
    48: require('./illustrated/48/growth.png') as ImageSourcePropType,
  },
  med: {
    24: require('./illustrated/24/med.png') as ImageSourcePropType,
    48: require('./illustrated/48/med.png') as ImageSourcePropType,
  },
  pump: {
    24: require('./illustrated/24/pump.png') as ImageSourcePropType,
    48: require('./illustrated/48/pump.png') as ImageSourcePropType,
  },
  sleep: {
    24: require('./illustrated/24/sleep.png') as ImageSourcePropType,
    48: require('./illustrated/48/sleep.png') as ImageSourcePropType,
  },
  solids: {
    24: require('./illustrated/24/solids.png') as ImageSourcePropType,
    48: require('./illustrated/48/solids.png') as ImageSourcePropType,
  },
  'supply-clothing': {
    24: require('./illustrated/24/supply-clothing.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-clothing.png') as ImageSourcePropType,
  },
  'supply-cream': {
    24: require('./illustrated/24/supply-cream.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-cream.png') as ImageSourcePropType,
  },
  'supply-formula': {
    24: require('./illustrated/24/supply-formula.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-formula.png') as ImageSourcePropType,
  },
  'supply-laundry': {
    24: require('./illustrated/24/supply-laundry.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-laundry.png') as ImageSourcePropType,
  },
  'supply-milk-storage': {
    24: require('./illustrated/24/supply-milk-storage.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-milk-storage.png') as ImageSourcePropType,
  },
  'supply-nipples': {
    24: require('./illustrated/24/supply-nipples.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-nipples.png') as ImageSourcePropType,
  },
  'supply-other': {
    24: require('./illustrated/24/supply-other.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-other.png') as ImageSourcePropType,
  },
  'supply-pacifiers': {
    24: require('./illustrated/24/supply-pacifiers.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-pacifiers.png') as ImageSourcePropType,
  },
  'supply-wipes': {
    24: require('./illustrated/24/supply-wipes.png') as ImageSourcePropType,
    48: require('./illustrated/48/supply-wipes.png') as ImageSourcePropType,
  },
  temp: {
    24: require('./illustrated/24/temp.png') as ImageSourcePropType,
    48: require('./illustrated/48/temp.png') as ImageSourcePropType,
  },
  tummy: {
    24: require('./illustrated/24/tummy.png') as ImageSourcePropType,
    48: require('./illustrated/48/tummy.png') as ImageSourcePropType,
  },
};
