/**
 * THE OWNER'S ILLUSTRATED ICONS — finished multi-color pictures, not tintable glyphs.
 *
 * Normalized into the app's icon box by `tools/ui/import-png-icons.mjs` (trimmed to their own
 * drawn pixels, then centred and scaled so every one fills the same fraction of the square,
 * because the masters put their content at a different offset and size in each file), and
 * rendered at two sizes, each at 2× and 3× (no 1× file: no supported phone is 1×, and the
 * generator's `SCALES` says what a 1× screen draws instead) — `illustratedTier` below says why
 * and which.
 * Twenty are the owner's redrawn sets of 2026-09-23 — the eleven module pictures ("slightly
 * redesigned and fix quality", one dark outline across the set) and then the nine supply shelves
 * ("also replace the supplies icons") — delivered as 10032 px print files and kept in the kit at
 * 2048. Two more were drawn in the repository on 2026-09-26 for what a care item is — a vitamin
 * (`care-vitamin`, two softgels) and anything else (`care-other`, a heart) — to the set's own
 * rules, because the owner asked for a picture on each kind and had drawn only the medicine and
 * the cream jar; their SVG sources and the one command that renders them are in
 * `tools/brand/render-care-pictures.mjs`, and a PNG of the owner's own under either name replaces
 * one.
 *
 * WHY THEY ARE NOT A REPLACEMENT FOR THE GLYPH SET, and this is the whole design of this file:
 *
 * **They stop being readable below about 28 px.** Rendered at 18 — the quick tile's size — the
 * breast pump is a smudge, the solids bowl is a blob and the sleeping moon loses its face. A
 * line glyph at 1.7 px on a 24 grid survives that reduction because it was drawn for it; an
 * illustration with four colors, a highlight and a sparkle does not. The app draws icons at
 * 15–16 on a timeline row, 18 on a quick tile and 20–23 in the nav, which is most of its icon
 * usage and all of it inside the range where these turn to mush.
 *
 * So `Icon` uses the illustration WHERE IT IS BIG ENOUGH TO READ and the tintable glyph
 * everywhere else, by size, with no screen having to know. The two sets are the same seven
 * subjects drawn twice, which is not duplication — it is the same reason an app ships a
 * 20 px and a 60 px app icon. Eleven subjects since 2026-09-22, when the owner drew bath,
 * breastfeeding, growth and medicine — twenty later the same day, when they drew the nine
 * supply shelves the log has no tile to lend (the other six borrow one; `SUPPLY_ICON` says
 * which). The supply catalog draws its glyph at 28, so every shelf is now a picture.
 *
 * THEY ALSO IGNORE `color`. A glyph is repainted per module, per scheme, per theme and in night
 * mode; these carry their own palette and cannot be. That is a real cost: in night mode the
 * amber screen gets a full-color picture, which is exactly what night mode exists to avoid. The
 * threshold keeps them off the surfaces night mode is for, but if this look is kept, night mode
 * has to fall back to the glyph regardless of size — noted here rather than solved, because
 * only eleven of the set exist so far.
 */
import type { IconName } from './paths';

/**
 * The smallest size an illustration is drawn at. Below this the glyph wins.
 *
 * 16 since 2026-09-22. It began at 28, measured off a 1x render where the set turned to mush
 * below that — but the owner looked at it on a real screen and asked for the illustrations
 * everywhere, with the icons BIGGER rather than the threshold higher. That is the better answer
 * to the same observation: the module surfaces now draw at 20-44 rather than 14-30, so the
 * pictures are shown at a size they survive, and 16 only keeps them off the few inline places
 * that sit beside a word (a 10-13pt chevron, a clock on a timestamp) where a picture would be
 * wrong whatever it looked like.
 */
export const ILLUSTRATED_MIN_SIZE = 16;

/**
 * WHICH NAMES HAVE A PICTURE. A plain list, deliberately — the `require()` map lives next door in
 * `illustrated.assets.ts` (generated by the importer, one entry per master) because the node test
 * runner cannot parse a PNG import (Metro can), and the rules worth testing are the threshold and
 * the tier, not the bytes. `tsc` holds the two together: the map is typed against this list.
 */
export const ILLUSTRATED_NAMES = [
  'bath',
  'bottle',
  'breast',
  'care-other',
  'care-vitamin',
  'diaper',
  'growth',
  'med',
  'pump',
  'sleep',
  'solids',
  'supply-clothing',
  'supply-cream',
  'supply-formula',
  'supply-laundry',
  'supply-milk-storage',
  'supply-nipples',
  'supply-other',
  'supply-pacifiers',
  'supply-wipes',
  'temp',
  'tummy',
] as const satisfies readonly IconName[];

export type IllustratedName = (typeof ILLUSTRATED_NAMES)[number];

const HAS_PICTURE = new Set<string>(ILLUSTRATED_NAMES);

/** Whether this name and size should be drawn as a picture rather than a repaintable glyph. */
export const drawIllustrated = (name: IconName, size: number): boolean =>
  size >= ILLUSTRATED_MIN_SIZE && HAS_PICTURE.has(name);

/**
 * THE TWO SIZES EACH PICTURE IS RENDERED AT, in points (2026-09-23, the owner: "fix quality").
 *
 * One 144 px file used to serve every size, and the phone shrank it. Android shrinks with
 * bilinear filtering and no mipmaps, which reads four source pixels per screen pixel however
 * far apart they are — so a picture drawn at 18 pt on a 3× phone, 54 px from 144, never has
 * close to half its pixels read, and its outlines step. The importer measured it (`tools/ui/import-png-icons.mjs`):
 * a render made for the size halves the error at 16 pt. Two tiers, not one per size, because the
 * sizes move with every design pass and a tier holds for any of them; not three, because a 32 pt
 * tier measured no better than 48 at 26–30.
 */
export const ILLUSTRATED_TIERS = [24, 48] as const;

export type IllustratedTier = (typeof ILLUSTRATED_TIERS)[number];

/**
 * The tier a size draws from: the smallest one at least as big, so a picture is only ever made
 * smaller on the screen, never blown up. 16–24 is the rows, the quick tiles, the capsule and the
 * care squares; everything above is the pebble, the catalog, the background doodles and the bubble.
 * Past 48 (a tablet's doodles) the largest is stretched — decoration at low alpha, where a
 * softened edge costs nothing.
 */
export const illustratedTier = (size: number): IllustratedTier => (size <= 24 ? 24 : 48);
