/**
 * GENERATED by tools/gen-app-slices.mjs from pricing.config.json — do not edit.
 * Change the source, then run `node tools/gen-app-slices.mjs`.
 *
 * The two parts of the config the app reads — the packages (`packages.ts`) and the length of
 * the welcome preview (`welcome.ts`) — so the rest of it, the store dashboards' mirror of the
 * plan matrix, is not bundled. Prices here are TARGETS for the store dashboards; a price a parent
 * sees comes from the store at runtime (CLAUDE.md rule 13).
 */
/** `packages`, whole and in the config's order. */
export const PRICING_PACKAGES = [
  {
    key: 'annual',
    product_id: 'nibble_plus_annual',
    entitlement: 'nibble_plus',
    target_price_usd: 39.99,
    period: 'P1Y',
    default_selected: true,
    discount_vs_monthly_pct: 33.2,
  },
  {
    key: 'monthly',
    product_id: 'nibble_plus_monthly',
    entitlement: 'nibble_plus',
    target_price_usd: 4.99,
    period: 'P1M',
    default_selected: false,
  },
];

/** `welcome_preview.days`. */
export const WELCOME_PREVIEW_DAYS = 14;
