/**
 * GENERATED by tools/gen-app-slices.mjs from ../store-listing.json — do not edit.
 * Change the source, then run `node tools/gen-app-slices.mjs`.
 *
 * `inApp`, the only part of the store listing the app renders (`IN_APP_STRINGS`), so the App
 * Store, Play, website and email drafts are not bundled.
 */
export const IN_APP = {
  $note:
    "The only brand strings the app itself renders. Short name only: the full store title never appears in app chrome. Every key here is one the app reads (apps/mobile/src, `IN_APP_STRINGS.<key>`); CuddleCue's trial banner, setup heads up, welcome card, export, email and notification names were not carried, because nothing in NibbleCue reads them and NibbleCue has no welcome trial.",
  signInTitle: 'NibbleCue',
  signInTagline: 'Your baby’s first foods, planned.',
  signInBlurbCreate:
    'Welcome to NibbleCue 💛\nSee what to offer at each meal, bring in the allergens one at a time, and share every meal with the people who feed your baby.',
  signInBlurbReturning: 'Sign in to pick up where your household left off.',
  paywallTitle: 'NibbleCue Plus',
  aboutTitle: 'About NibbleCue',
  $storyNote:
    "Who made it. The studio's lines are the owner's own, carried from CuddleCue unchanged (2026-09-27 and 2026-09-28): `familyLine`, the tagline in `footerLine` (\"By new parents, for every parent.\"), `aboutStoryTitle`, `aboutPlus`, `contactNote` and `planWhy`. Same family, same studio. Two are DRAFTS for the owner, because CuddleCue's words were not true of NibbleCue: `aboutStory` (CuddleCue's second sentence was about keeping track through the long nights) and `aboutArt` (CuddleCue's said the pictures are Mom's own drawings, and NibbleCue's artwork is placeholder art until the designer's kit arrives, brand.json `assets.$status`). The signInTagline is brand.json `tagline`, itself a proposal (`$taglineNote`).",
  familyLine: 'Dad develops · Mom designs · Baby approves',
  footerLine: 'By new parents, for every parent.',
  aboutStoryTitle: 'Our story',
  aboutStory:
    'We became parents in 2026 and we’re still in the thick of it. We built this to make first foods a little easier, for your family and for ours.',
  aboutArt: 'The pictures here are stand-ins until our own drawings are ready.',
  aboutPlus:
    'Plus pays for the servers, the replies when you write and what we build next, so we can keep going and still do what’s best for our own kids. As they grow, what we make will grow with them.',
  contactNote: 'One of us will answer, usually after bedtime.',
  planWhy: 'Plus pays for the servers, the replies when you write and what we build next.',
};
