#!/usr/bin/env python3
"""
IMPORT THE FOOD PHOTOS into the app (docs/FOOD_IMAGES.md).

    python3 tools/foods/import-food-images.py <folder of photos>

Each photo is named by its food id, the first column of tools/foods/food-image-prompts.csv
(`sweet-potato.png`, `avocado.jpg`, `beef.webp` ...). Every photo is center-cropped to a square,
resized to 512 x 512 and saved as a JPEG (quality 82, about 40 to 60 KB) in
apps/mobile/assets/foods/<id>.jpg, and apps/mobile/src/nibble/foodImages.generated.ts is written
again with one entry per photo now in that folder. A file whose name is not a food id is reported
and skipped, so a typo never ships a photo under the wrong food. Run it again any time: photos
already imported stay unless a new one replaces them.
"""
import csv
import sys
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'apps' / 'mobile' / 'assets' / 'foods'
MAP = ROOT / 'apps' / 'mobile' / 'src' / 'nibble' / 'foodImages.generated.ts'
PROMPTS = ROOT / 'tools' / 'foods' / 'food-image-prompts.csv'
SIZE = 512
EXTS = {'.jpg', '.jpeg', '.png', '.webp'}

HEADER = '''/**
 * GENERATED by tools/foods/import-food-images.py from the photos in apps/mobile/assets/foods/,
 * one per food id. Do not edit: drop the photos in a folder and run the tool
 * (docs/FOOD_IMAGES.md). A food with no photo here is drawn with its category's glyph instead.
 */
import type { ImageSourcePropType } from 'react-native';
'''


def food_ids() -> set[str]:
    with PROMPTS.open(newline='', encoding='utf-8') as f:
        return {row['id'] for row in csv.DictReader(f)}


def square(img: Image.Image) -> Image.Image:
    img = ImageOps.exif_transpose(img).convert('RGB')
    side = min(img.size)
    left = (img.width - side) // 2
    top = (img.height - side) // 2
    return img.crop((left, top, left + side, top + side)).resize((SIZE, SIZE), Image.LANCZOS)


def write_map() -> int:
    ids = sorted(p.stem for p in OUT.glob('*.jpg'))
    lines = [HEADER, 'export const FOOD_IMAGES: Readonly<Record<string, ImageSourcePropType>> = {']
    for i in ids:
        lines.append(f"  '{i}': require('../../assets/foods/{i}.jpg'),")
    lines.append('};')
    if not ids:
        lines = [HEADER, 'export const FOOD_IMAGES: Readonly<Record<string, ImageSourcePropType>> = {};']
    MAP.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return len(ids)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = Path(sys.argv[1])
    known = food_ids()
    OUT.mkdir(parents=True, exist_ok=True)
    done, skipped = 0, []
    for p in sorted(src.iterdir()):
        if p.suffix.lower() not in EXTS:
            continue
        if p.stem not in known:
            skipped.append(p.name)
            continue
        square(Image.open(p)).save(OUT / f'{p.stem}.jpg', 'JPEG', quality=82, optimize=True, progressive=True)
        done += 1
    total = write_map()
    print(f'imported {done} photo(s); {total} of {len(known)} foods now have one')
    if skipped:
        print('skipped (not a food id): ' + ', '.join(skipped))
    missing = sorted(known - {p.stem for p in OUT.glob('*.jpg')})
    if missing:
        print(f'still without a photo ({len(missing)}): ' + ', '.join(missing[:20]) + (' ...' if len(missing) > 20 else ''))


if __name__ == '__main__':
    main()
