/**
 * GENERATED by tools/foods/import-food-images.py from the photos in apps/mobile/assets/foods/,
 * one per food id. Do not edit: drop the photos in a folder and run the tool
 * (docs/FOOD_IMAGES.md). A food with no photo here is drawn with its category's glyph instead.
 */
import type { ImageSourcePropType } from 'react-native';

export const FOOD_IMAGES: Readonly<Record<string, ImageSourcePropType>> = {};
