/**
 * GENERATED by tools/brand/render-card-art.mjs — do not edit.
 *
 * What each card background measures, from the shipped file itself: the ink the owner drew it
 * with, the smallest veil — in the artwork's own deepened hue — that takes that ink to WCAG's
 * large-text bar across the content column, and the contrast the pair actually reaches, from an
 * exact composite rather than an approximation — over the picture as it is drawn on its own
 * ground, and on that ground alone, for the moments the picture is not there.
 * `pnpm check:card-art` regenerates and fails on a difference, so swapping an artwork cannot
 * quietly make a card unreadable.
 */
/** WCAG AA for body text — what a card's accent figure clears. */
export const AA_TEXT = 4.5;
/** WCAG's large-text bar — what the veil is solved for. The tool says at length why. */
export const AA_LARGE = 3;
/** The bounds the content-column search ran between. */
export const CONTENT_MAX = 0.72;
export const CONTENT_MIN = 0.4;
/** The veil cap every card gets unless its own slot raises it, and the ceiling none may pass. */
export const VEIL_MAX = 0.2;
export const VEIL_CEILING = 0.26;
/** The narrowest content column any slot may ask the search to consider. */
export const CONTENT_FLOOR = 0.34;

export interface ArtMeasurement {
  /**
   * The shipped file, in `apps/mobile/assets/card-art`: a JPEG (the tool's header says why and
   * what it measured). `cardArt.ts` imports exactly this name.
   */
  file: string;
  /**
   * The owner's master it is rendered from, in `assets/brand/kit/07-card-backgrounds` — which a
   * test reads at this size, since the shipped file is a JPEG (`cardArtParts.test.ts` says why).
   */
  master: string;
  /**
   * A DARK OR NIGHT VERSION (2026-09-29): the picture it is a version `of`, and which, drawn from
   * that picture's master by `tools/brand/card-art-versions.mjs`. Absent on the owner's own seven.
   */
  of?: string;
  version?: 'dark' | 'night';
  /** A Night version's one amber tone: its module's color in the Night palette. */
  tone?: string;
  /** The bar this card's words were held to: 3 over the owner's drawing for a light ink, else 4.5. */
  bar: number;
  /** The rendered picture's pixels. */
  width: number;
  height: number;
  /** Which art ink the card's content takes: the day pictures' two, and Night's amber. */
  ink: 'light' | 'dark' | 'amber';
  /** 0 when the bare artwork already clears the bar unaided. */
  veil: number;
  /**
   * THE VEIL'S COLOR: this artwork's own darkest hue, deepened. Never a neutral — a gray wash
   * over a saturated ground desaturates it, and the owner saw their orange arrive as brown.
   */
  veilColor: string;
  /** The widest leftmost share of the card this artwork can carry text on. */
  contentFraction: number;
  /** Where the veil has faded to nothing. */
  veilEnd: number;
  /** What the ink reaches over the veiled artwork, worst pixel in the content column. */
  contrast: number;
  /**
   * THE PICTURE'S OWN GROUND (2026-09-29): the color it is painted in where a card's words always
   * sit, drawn solid under it so the card reads the same before the picture arrives, if it never
   * does, and under the parts of it that are translucent (the stash summary is, everywhere).
   */
  ground: string;
  /** What the ink reaches on that ground alone, under the column's veil. */
  groundContrast: number;
  /**
   * How far the card's words run over the picture: `column`, capped at `contentFraction` (Today's
   * pair), or `card`, across the whole of it (the stash summary), measured across the whole of it.
   */
  span: 'column' | 'card';
  /**
   * WHERE THE OWNER KEPT THEIR INK UNDER THE BAR ACROSS THE COLUMN TOO (2026-09-27: *"Keep white.
   * i dont see what the fuss is all about, they look fine in my eyes."*): the least `contrast` is
   * owed at, from the tool's ledger — no veil under the cap lifts this ground to the bar, so the
   * card carries the cap and the shortfall is recorded rather than hidden. Absent on every card
   * whose column clears it.
   */
  contrastOwed?: number;
  /** The cap the search ran under for this artwork: VEIL_MAX unless its slot raised it. */
  veilMax: number;
  /** The floor it stopped at: CONTENT_MIN unless its slot lowered it. */
  contentMin: number;
  /** A second measured color for the card's figure, where the artwork carries one. */
  accent?: 'gold' | 'green' | 'honey' | 'mint' | 'amber';
  accentContrast?: number;
  /** The accent on the ground alone. */
  accentGroundContrast?: number;
  /** A card whose words cross the whole picture (`span: 'card'`): the ink and the accent over all of it. */
  cardContrast?: number;
  accentCardContrast?: number;
}

export const ART_MEASURED = {
  breastfeed: {
    file: 'breastfeed.jpg',
    master: 'cuddlecue-breastfeeding-full-background.png',
    bar: 3,
    width: 1280,
    height: 576,
    ink: 'light',
    veil: 0.16,
    veilColor: '#6e2637',
    contentFraction: 0.51,
    veilEnd: 0.71,
    contrast: 3.02,
    ground: '#f76a7d',
    groundContrast: 3.45,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
  },
  sleep: {
    file: 'sleep.jpg',
    master: 'cuddlecue-sleeping-full-background.png',
    bar: 3,
    width: 1280,
    height: 427,
    ink: 'light',
    veil: 0.18,
    veilColor: '#433961',
    contentFraction: 0.35,
    veilEnd: 0.55,
    contrast: 3.03,
    ground: '#a58ce8',
    groundContrast: 3.45,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.34,
  },
  pump: {
    file: 'pump.jpg',
    master: 'cuddlecue-pumping-full-background.png',
    bar: 3,
    width: 1280,
    height: 427,
    ink: 'light',
    veil: 0.2,
    veilColor: '#16473b',
    contentFraction: 0.41,
    veilEnd: 0.61,
    contrast: 3.01,
    ground: '#3b9d82',
    groundContrast: 4.09,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
  },
  tummy: {
    file: 'tummy.jpg',
    master: 'cuddlecue-tummy-time-full-background.png',
    bar: 3,
    width: 1280,
    height: 427,
    ink: 'light',
    veil: 0.2,
    veilColor: '#27415d',
    contentFraction: 0.34,
    veilEnd: 0.54,
    contrast: 2.62,
    ground: '#6baef5',
    groundContrast: 3.02,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.34,
    contrastOwed: 2.61,
  },
  stash: {
    file: 'stash.jpg',
    master: 'cuddlecue-milk-stash-full-background.png',
    bar: 4.5,
    width: 1280,
    height: 320,
    ink: 'dark',
    veil: 0,
    veilColor: '#4a3e25',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 12.29,
    ground: '#fde29a',
    groundContrast: 14.57,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'gold',
    accentContrast: 5.67,
    accentGroundContrast: 6.73,
  },
  stashCard: {
    file: 'stashCard.jpg',
    master: 'cuddlecue-milk-stash-summary-background.png',
    bar: 4.5,
    width: 1280,
    height: 533,
    ink: 'dark',
    veil: 0,
    veilColor: '#473f27',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 12.06,
    ground: '#f9ebb9',
    groundContrast: 15.53,
    span: 'card',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'gold',
    accentContrast: 5.57,
    accentGroundContrast: 7.17,
    cardContrast: 10.37,
    accentCardContrast: 4.79,
  },
  shopping: {
    file: 'shopping.jpg',
    master: 'cuddlecue-shopping-list-full-background.png',
    bar: 4.5,
    width: 1280,
    height: 320,
    ink: 'dark',
    veil: 0,
    veilColor: '#39422c',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 11.15,
    ground: '#d1e5a6',
    groundContrast: 13.64,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'green',
    accentContrast: 5.49,
    accentGroundContrast: 6.71,
  },
  stashDark: {
    file: 'stashDark.jpg',
    master: 'cuddlecue-milk-stash-full-background.png',
    of: 'stash',
    version: 'dark',
    bar: 4.5,
    width: 1280,
    height: 320,
    ink: 'light',
    veil: 0,
    veilColor: '#2d2109',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 12.41,
    ground: '#2f230a',
    groundContrast: 15.38,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'honey',
    accentContrast: 9.18,
    accentGroundContrast: 11.38,
  },
  stashCardDark: {
    file: 'stashCardDark.jpg',
    master: 'cuddlecue-milk-stash-summary-background.png',
    of: 'stashCard',
    version: 'dark',
    bar: 4.5,
    width: 1280,
    height: 533,
    ink: 'light',
    veil: 0,
    veilColor: '#271c06',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 6.56,
    ground: '#2c210a',
    groundContrast: 15.8,
    span: 'card',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'honey',
    accentContrast: 4.86,
    accentGroundContrast: 11.7,
    cardContrast: 6.37,
    accentCardContrast: 4.72,
  },
  shoppingDark: {
    file: 'shoppingDark.jpg',
    master: 'cuddlecue-shopping-list-full-background.png',
    of: 'shopping',
    version: 'dark',
    bar: 4.5,
    width: 1280,
    height: 320,
    ink: 'light',
    veil: 0,
    veilColor: '#1a2715',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 11.99,
    ground: '#1b2917',
    groundContrast: 15.26,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'mint',
    accentContrast: 8.37,
    accentGroundContrast: 10.65,
  },
  stashNight: {
    file: 'stashNight.jpg',
    master: 'cuddlecue-milk-stash-full-background.png',
    of: 'stash',
    version: 'night',
    tone: '#CE9A55',
    bar: 4.5,
    width: 1280,
    height: 320,
    ink: 'amber',
    veil: 0,
    veilColor: '#100b05',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 9.62,
    ground: '#181007',
    groundContrast: 10.49,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'amber',
    accentContrast: 9.62,
    accentGroundContrast: 10.49,
  },
  stashCardNight: {
    file: 'stashCardNight.jpg',
    master: 'cuddlecue-milk-stash-summary-background.png',
    of: 'stashCard',
    version: 'night',
    tone: '#CE9A55',
    bar: 4.5,
    width: 1280,
    height: 533,
    ink: 'amber',
    veil: 0,
    veilColor: '#100b05',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 4.75,
    ground: '#1a1208',
    groundContrast: 10.32,
    span: 'card',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'amber',
    accentContrast: 4.75,
    accentGroundContrast: 10.32,
    cardContrast: 4.53,
    accentCardContrast: 4.53,
  },
  shoppingNight: {
    file: 'shoppingNight.jpg',
    master: 'cuddlecue-shopping-list-full-background.png',
    of: 'shopping',
    version: 'night',
    tone: '#A3A05C',
    bar: 4.5,
    width: 1280,
    height: 320,
    ink: 'amber',
    veil: 0,
    veilColor: '#141408',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 9.53,
    ground: '#151509',
    groundContrast: 10.24,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
    accent: 'amber',
    accentContrast: 9.53,
    accentGroundContrast: 10.24,
  },
  breastfeedNight: {
    file: 'breastfeedNight.jpg',
    master: 'cuddlecue-breastfeeding-full-background.png',
    of: 'breastfeed',
    version: 'night',
    tone: '#B78B59',
    bar: 3,
    width: 1280,
    height: 576,
    ink: 'amber',
    veil: 0,
    veilColor: '#0a0100',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 4.53,
    ground: '#1a1108',
    groundContrast: 10.38,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
  },
  sleepNight: {
    file: 'sleepNight.jpg',
    master: 'cuddlecue-sleeping-full-background.png',
    of: 'sleep',
    version: 'night',
    tone: '#BEA576',
    bar: 3,
    width: 1280,
    height: 427,
    ink: 'amber',
    veil: 0,
    veilColor: '#040000',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 4.69,
    ground: '#191307',
    groundContrast: 10.29,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
  },
  pumpNight: {
    file: 'pumpNight.jpg',
    master: 'cuddlecue-pumping-full-background.png',
    of: 'pump',
    version: 'night',
    tone: '#B8905F',
    bar: 3,
    width: 1280,
    height: 427,
    ink: 'amber',
    veil: 0,
    veilColor: '#070000',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 4.67,
    ground: '#181007',
    groundContrast: 10.49,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
  },
  tummyNight: {
    file: 'tummyNight.jpg',
    master: 'cuddlecue-tummy-time-full-background.png',
    of: 'tummy',
    version: 'night',
    tone: '#C1AE81',
    bar: 3,
    width: 1280,
    height: 427,
    ink: 'amber',
    veil: 0,
    veilColor: '#040000',
    contentFraction: 0.72,
    veilEnd: 0.92,
    contrast: 4.62,
    ground: '#171307',
    groundContrast: 10.34,
    span: 'column',
    veilMax: 0.2,
    contentMin: 0.4,
  },
} as const satisfies Record<string, ArtMeasurement>;
