/**
 * GENERATED by tools/brand/render-stash-icons.mjs — do not edit.
 *
 * The pixel size of each shipped storage-place icon, so the app can hand <Image> an explicit
 * width and height rather than letting the asset's own size decide the layout.
 */
export interface StashIconSize {
  width: number;
  height: number;
}

/** The box every one of them was fitted into. */
export const STASH_ICON_PX = 96;

export const STASH_ICON_SIZE = {
  ROOM: {
    width: 96,
    height: 96,
  },
  FRIDGE: {
    width: 96,
    height: 96,
  },
  FREEZER: {
    width: 96,
    height: 96,
  },
  DEEP_FREEZER: {
    width: 96,
    height: 96,
  },
  THAWED: {
    width: 96,
    height: 96,
  },
} as const satisfies Record<string, StashIconSize>;
